### ISSUE TITLE
the result of demo is like this, do I need to change the array of board_transform according to my dicom files? 

### ISSUE THREAD

**Issue by ziggyan** [michaelitvin/CT-projection#1]
![image](https://user-images.githubusercontent.com/53549794/64328946-f295ed00-d000-11e9-9657-15d04e4753da.png)

**Comment by ziggyan** [comment]
`xray_sag = ctp.proj_ct_to_xray(light_pos, board, np.linalg.inv(ct_matrix), ct_img3d)
` change to `xray_ax = ctp.proj_ct_to_xray(light_pos, board, ct_matrix, ct_img3d)
`,

**Comment by MeiQD** [comment]
yes
